// Recipe Data
const recipes = [
  {
    id: 1,
    slug: 'creamy-garlic-chicken-pasta',
    title: 'Creamy Garlic Chicken Pasta',
    description: 'A rich and creamy pasta dish with tender chicken and aromatic garlic.',
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    totalTime: '30 minutes',
    servings: 4,
    difficulty: 'Easy',
    category: 'Quick Dinner',
    image: 'https://images.unsplash.com/photo-1748012199657-3f34292cdf70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '1 lb chicken breast, cubed',
      '12 oz fettuccine pasta',
      '4 cloves garlic, minced',
      '2 cups heavy cream',
      '1 cup parmesan cheese, grated',
      '2 tbsp olive oil',
      '1 tsp Italian seasoning',
      'Salt and pepper to taste',
      'Fresh parsley for garnish',
    ],
    instructions: [
      'Cook pasta according to package directions. Drain and set aside.',
      'Heat olive oil in a large skillet over medium-high heat.',
      'Season chicken with salt, pepper, and Italian seasoning. Cook until golden and cooked through, about 6-7 minutes.',
      'Add minced garlic and cook for 1 minute until fragrant.',
      'Pour in heavy cream and bring to a gentle simmer.',
      'Stir in parmesan cheese until melted and sauce is creamy.',
      'Add cooked pasta and toss to coat evenly.',
      'Garnish with fresh parsley and serve immediately.',
    ],
    tips: [
      'Use freshly grated parmesan for the best flavor and texture.',
      'Don\'t let the cream boil rapidly as it may separate.',
      'Add a splash of pasta water if the sauce is too thick.',
    ],
    nutrition: {
      calories: '650 kcal',
      protein: '42g',
      carbs: '48g',
      fat: '32g',
    },
  },
  {
    id: 2,
    slug: 'classic-american-cheeseburger',
    title: 'Classic American Cheeseburger',
    description: 'A juicy, flavorful cheeseburger with all the classic toppings.',
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    totalTime: '25 minutes',
    servings: 4,
    difficulty: 'Easy',
    category: 'Comfort Food',
    image: 'https://images.unsplash.com/photo-1679344600845-410685891214?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '1 lb ground beef (80/20)',
      '4 burger buns, toasted',
      '4 slices cheddar cheese',
      'Lettuce leaves',
      '1 tomato, sliced',
      '1 onion, sliced',
      'Pickles',
      'Ketchup and mustard',
      'Salt and pepper',
    ],
    instructions: [
      'Season the ground beef with salt and pepper.',
      'Divide beef into 4 equal portions and form into patties.',
      'Make a small indent in the center of each patty to prevent puffing.',
      'Heat grill or skillet to medium-high heat.',
      'Cook patties for 4-5 minutes per side for medium doneness.',
      'Add cheese slices in the last minute of cooking and cover to melt.',
      'Toast burger buns on the grill for 1-2 minutes.',
      'Assemble burgers with lettuce, tomato, onion, pickles, and condiments.',
    ],
    tips: [
      'Don\'t press down on the burgers while cooking - this squeezes out juices.',
      'Let burgers rest for 2-3 minutes before serving.',
      'For extra flavor, add a pinch of garlic powder to the beef.',
    ],
    nutrition: {
      calories: '520 kcal',
      protein: '32g',
      carbs: '35g',
      fat: '28g',
    },
  },
  {
    id: 3,
    slug: 'honey-glazed-salmon',
    title: 'Honey Glazed Salmon',
    description: 'Sweet and savory salmon with a beautiful honey glaze.',
    prepTime: '5 minutes',
    cookTime: '15 minutes',
    totalTime: '20 minutes',
    servings: 4,
    difficulty: 'Easy',
    category: 'Healthy',
    image: 'https://images.unsplash.com/photo-1704007573697-6a516da421ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '4 salmon fillets (6 oz each)',
      '3 tbsp honey',
      '2 tbsp soy sauce',
      '2 tbsp lemon juice',
      '2 cloves garlic, minced',
      '1 tbsp olive oil',
      'Salt and pepper to taste',
      'Sesame seeds for garnish',
      'Green onions, chopped',
    ],
    instructions: [
      'Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper.',
      'In a small bowl, whisk together honey, soy sauce, lemon juice, and garlic.',
      'Season salmon fillets with salt and pepper.',
      'Heat olive oil in an oven-safe skillet over medium-high heat.',
      'Sear salmon skin-side up for 2-3 minutes.',
      'Flip salmon and brush with honey glaze.',
      'Transfer skillet to oven and bake for 8-10 minutes until cooked through.',
      'Garnish with sesame seeds and green onions before serving.',
    ],
    tips: [
      'Salmon is done when it flakes easily with a fork.',
      'Reserve some glaze to drizzle over cooked salmon.',
      'Serve with steamed rice and vegetables for a complete meal.',
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '36g',
      carbs: '18g',
      fat: '18g',
    },
  },
  {
    id: 4,
    slug: 'homemade-chicken-alfredo',
    title: 'Homemade Chicken Alfredo',
    description: 'Classic Italian-American favorite with a rich, creamy sauce.',
    prepTime: '15 minutes',
    cookTime: '25 minutes',
    totalTime: '40 minutes',
    servings: 6,
    difficulty: 'Medium',
    category: 'Comfort Food',
    image: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '1 lb chicken breast, sliced',
      '1 lb fettuccine pasta',
      '4 tbsp butter',
      '2 cups heavy cream',
      '2 cups parmesan cheese, grated',
      '4 cloves garlic, minced',
      '1 tsp Italian seasoning',
      'Salt and pepper to taste',
      'Fresh parsley, chopped',
    ],
    instructions: [
      'Cook fettuccine according to package directions. Reserve 1 cup pasta water.',
      'Season chicken with salt, pepper, and Italian seasoning.',
      'Cook chicken in a large skillet until golden and cooked through. Set aside.',
      'In the same skillet, melt butter and sauté garlic for 1 minute.',
      'Pour in heavy cream and bring to a gentle simmer.',
      'Gradually add parmesan cheese, stirring constantly until smooth.',
      'Add cooked pasta and toss to coat. Use pasta water if needed to thin sauce.',
      'Add chicken back to the pan and toss everything together.',
      'Garnish with fresh parsley and extra parmesan.',
    ],
    tips: [
      'Use room temperature cream to prevent curdling.',
      'Add cheese slowly and stir constantly for a smooth sauce.',
      'This dish is best served immediately while sauce is creamy.',
    ],
    nutrition: {
      calories: '720 kcal',
      protein: '38g',
      carbs: '52g',
      fat: '38g',
    },
  },
  {
    id: 5,
    slug: 'crispy-baked-chicken-wings',
    title: 'Crispy Baked Chicken Wings',
    description: 'Perfectly crispy wings without deep frying.',
    prepTime: '10 minutes',
    cookTime: '45 minutes',
    totalTime: '55 minutes',
    servings: 4,
    difficulty: 'Easy',
    category: 'Family Meals',
    image: 'https://images.unsplash.com/photo-1712286928542-17af515d3dcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '2 lbs chicken wings',
      '2 tbsp baking powder',
      '1 tsp salt',
      '1 tsp garlic powder',
      '1 tsp paprika',
      '1/2 tsp black pepper',
      'Your favorite wing sauce',
      'Ranch or blue cheese for dipping',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C). Line a baking sheet with parchment paper.',
      'Pat chicken wings completely dry with paper towels.',
      'In a large bowl, mix baking powder, salt, garlic powder, paprika, and pepper.',
      'Toss wings in the seasoning mixture until evenly coated.',
      'Arrange wings on baking sheet in a single layer, not touching.',
      'Bake for 45 minutes, flipping halfway through, until golden and crispy.',
      'Toss with your favorite sauce or serve plain with dipping sauce.',
    ],
    tips: [
      'Baking powder (not baking soda) is the secret to crispy skin.',
      'Make sure wings are completely dry before seasoning.',
      'Don\'t overcrowd the pan - this creates steam and prevents crisping.',
    ],
    nutrition: {
      calories: '420 kcal',
      protein: '38g',
      carbs: '2g',
      fat: '28g',
    },
  },
  {
    id: 6,
    slug: 'classic-pancakes',
    title: 'Classic Pancakes',
    description: 'Fluffy, golden pancakes perfect for breakfast.',
    prepTime: '5 minutes',
    cookTime: '15 minutes',
    totalTime: '20 minutes',
    servings: 4,
    difficulty: 'Easy',
    category: 'Breakfast',
    image: 'https://images.unsplash.com/photo-1584278858944-7c34f1d94db0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '2 cups all-purpose flour',
      '2 tbsp sugar',
      '2 tsp baking powder',
      '1 tsp salt',
      '2 eggs',
      '1 3/4 cups milk',
      '4 tbsp melted butter',
      '1 tsp vanilla extract',
      'Butter and maple syrup for serving',
    ],
    instructions: [
      'In a large bowl, whisk together flour, sugar, baking powder, and salt.',
      'In another bowl, beat eggs and add milk, melted butter, and vanilla.',
      'Pour wet ingredients into dry ingredients and stir until just combined. Don\'t overmix.',
      'Heat a griddle or skillet over medium heat and lightly grease.',
      'Pour 1/4 cup batter for each pancake.',
      'Cook until bubbles form on surface and edges look set, about 2-3 minutes.',
      'Flip and cook until golden brown on the other side, about 1-2 minutes.',
      'Serve warm with butter and maple syrup.',
    ],
    tips: [
      'Don\'t overmix the batter - lumps are okay and result in fluffier pancakes.',
      'Let batter rest for 5 minutes before cooking.',
      'Keep cooked pancakes warm in a 200°F oven while cooking the rest.',
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '12g',
      carbs: '52g',
      fat: '14g',
    },
  },
  {
    id: 7,
    slug: 'bbq-pulled-pork-sandwich',
    title: 'BBQ Pulled Pork Sandwich',
    description: 'Tender, slow-cooked pulled pork with tangy BBQ sauce.',
    prepTime: '15 minutes',
    cookTime: '6 hours',
    totalTime: '6 hours 15 minutes',
    servings: 8,
    difficulty: 'Medium',
    category: 'Comfort Food',
    image: 'https://images.unsplash.com/photo-1757961048411-73703e333d25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '4 lbs pork shoulder',
      '2 tbsp brown sugar',
      '2 tbsp paprika',
      '1 tbsp garlic powder',
      '1 tbsp onion powder',
      '1 tsp cayenne pepper',
      'Salt and pepper to taste',
      '2 cups BBQ sauce',
      '8 hamburger buns',
      'Coleslaw for topping',
    ],
    instructions: [
      'Mix brown sugar, paprika, garlic powder, onion powder, cayenne, salt, and pepper.',
      'Rub spice mixture all over pork shoulder.',
      'Place pork in slow cooker and cook on low for 6-8 hours until very tender.',
      'Remove pork and shred with two forks.',
      'Discard excess fat and return meat to slow cooker.',
      'Add BBQ sauce and mix well. Cook on low for 30 more minutes.',
      'Toast buns and fill with pulled pork.',
      'Top with coleslaw and serve.',
    ],
    tips: [
      'Pork is done when it easily shreds with a fork.',
      'Save the cooking liquid to add moisture if needed.',
      'This freezes beautifully for easy meals later.',
    ],
    nutrition: {
      calories: '580 kcal',
      protein: '42g',
      carbs: '48g',
      fat: '22g',
    },
  },
  {
    id: 8,
    slug: 'chocolate-chip-cookies',
    title: 'Chocolate Chip Cookies',
    description: 'Classic homemade cookies that are crispy on the edges and chewy in the center.',
    prepTime: '15 minutes',
    cookTime: '12 minutes',
    totalTime: '27 minutes',
    servings: 24,
    difficulty: 'Easy',
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '2 1/4 cups all-purpose flour',
      '1 tsp baking soda',
      '1 tsp salt',
      '1 cup butter, softened',
      '3/4 cup white sugar',
      '3/4 cup brown sugar',
      '2 eggs',
      '2 tsp vanilla extract',
      '2 cups chocolate chips',
    ],
    instructions: [
      'Preheat oven to 375°F (190°C).',
      'In a bowl, whisk together flour, baking soda, and salt.',
      'In a large bowl, cream together butter and both sugars until fluffy.',
      'Beat in eggs one at a time, then add vanilla.',
      'Gradually mix in flour mixture until just combined.',
      'Fold in chocolate chips.',
      'Drop rounded tablespoons of dough onto ungreased baking sheets.',
      'Bake for 10-12 minutes until edges are golden brown.',
      'Cool on baking sheet for 2 minutes before transferring to wire rack.',
    ],
    tips: [
      'Chill dough for 30 minutes for thicker cookies.',
      'Don\'t overbake - cookies will continue to cook on the pan.',
      'Use a mix of milk and dark chocolate chips for extra flavor.',
    ],
    nutrition: {
      calories: '180 kcal',
      protein: '2g',
      carbs: '24g',
      fat: '9g',
    },
  },
  {
    id: 9,
    slug: 'mediterranean-grilled-chicken',
    title: 'Mediterranean Grilled Chicken',
    description: 'Juicy grilled chicken with Mediterranean herbs and spices.',
    prepTime: '10 minutes',
    cookTime: '20 minutes',
    totalTime: '30 minutes',
    servings: 4,
    difficulty: 'Easy',
    category: 'Healthy',
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '4 chicken breasts',
      '1/4 cup olive oil',
      '3 tbsp lemon juice',
      '3 cloves garlic, minced',
      '2 tsp dried oregano',
      '1 tsp dried basil',
      '1 tsp paprika',
      'Salt and pepper to taste',
      'Fresh herbs for garnish',
    ],
    instructions: [
      'In a bowl, whisk together olive oil, lemon juice, garlic, oregano, basil, and paprika.',
      'Season chicken breasts with salt and pepper.',
      'Add chicken to marinade and coat well. Marinate for at least 30 minutes.',
      'Preheat grill to medium-high heat.',
      'Remove chicken from marinade and grill for 6-7 minutes per side.',
      'Chicken is done when internal temperature reaches 165°F.',
      'Let rest for 5 minutes before slicing.',
      'Garnish with fresh herbs and serve.',
    ],
    tips: [
      'Pound chicken to even thickness for uniform cooking.',
      'Don\'t overcook or chicken will be dry.',
      'Serve with Greek salad and rice for a complete meal.',
    ],
    nutrition: {
      calories: '320 kcal',
      protein: '42g',
      carbs: '3g',
      fat: '15g',
    },
  },
  {
    id: 10,
    slug: 'homemade-beef-tacos',
    title: 'Homemade Beef Tacos',
    description: 'Flavorful seasoned beef tacos with all your favorite toppings.',
    prepTime: '10 minutes',
    cookTime: '15 minutes',
    totalTime: '25 minutes',
    servings: 6,
    difficulty: 'Easy',
    category: 'Family Meals',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
    ingredients: [
      '1 lb ground beef',
      '1 tbsp chili powder',
      '1 tsp cumin',
      '1 tsp paprika',
      '1/2 tsp garlic powder',
      '1/2 tsp onion powder',
      'Salt and pepper to taste',
      '12 taco shells',
      'Shredded lettuce, cheese, tomatoes, sour cream',
    ],
    instructions: [
      'Heat a large skillet over medium-high heat.',
      'Add ground beef and cook until browned, breaking up with a spoon.',
      'Drain excess fat.',
      'Add chili powder, cumin, paprika, garlic powder, onion powder, salt, and pepper.',
      'Stir in 1/2 cup water and simmer for 5 minutes until liquid is absorbed.',
      'Warm taco shells according to package directions.',
      'Fill shells with seasoned beef.',
      'Top with lettuce, cheese, tomatoes, and sour cream.',
    ],
    tips: [
      'Add a squeeze of lime juice for extra freshness.',
      'Make your own taco seasoning to control sodium.',
      'Try ground turkey or chicken for a lighter option.',
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '24g',
      carbs: '28g',
      fat: '18g',
    },
  },
];

const featuredRecipes = recipes.slice(0, 8);
